# Generated by Django 5.1.3 on 2024-11-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_stickynote_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='user',
        ),
    ]
