# Generated by Django 5.1.3 on 2024-11-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_notebook_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
