# Generated by Django 5.1.3 on 2024-11-29 13:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
